# Generated by Django 2.2.1 on 2019-09-08 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20190823_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='refer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commentOnComment', to='images.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='images.Image'),
        ),
    ]
