# Generated by Django 2.2.1 on 2019-09-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20190908_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='refer',
        ),
    ]
