# Generated by Django 2.2.1 on 2019-09-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20190909_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='refer',
            new_name='referComment',
        ),
    ]
