# Generated by Django 2.2.1 on 2019-09-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_auto_20190909_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='referComment',
        ),
    ]
