# Generated by Django 2.2.1 on 2019-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_auto_20190910_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
