# Generated by Django 2.2.1 on 2019-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stdntnum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
